
name: PR for release
# Limit it to just creating the PR.
permissions: 
  contents:  read
  pull-requests: write
on:
  workflow_dispatch: 

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: create pull request
        # https://cli.github.com/manual/gh_pr_create
        run: gh pr create -B release -H master --label 'release' --title 'Release Request' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

